# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shedule.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shedule.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rshedule.proto\"\xd1\x03\n\x03\x44\x61y\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x07\x63lasses\x18\x02 \x03(\x0b\x32\n.Day.Class\x1a\x9e\x03\n\x05\x43lass\x12%\n\x08position\x18\x01 \x01(\x0b\x32\x13.Day.Class.Position\x12\x1f\n\x05place\x18\x02 \x01(\x0b\x32\x10.Day.Class.Place\x12+\n\x06_class\x18\x03 \x01(\x0b\x32\x1b.Day.Class.ClassDescription\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x1a\x37\n\x08Position\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x1d\n\x04week\x18\x02 \x01(\x0e\x32\x0f.Day.Class.Week\x1a*\n\x05Place\x12\x10\n\x08\x61uditory\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x1aW\n\x10\x43lassDescription\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.Day.Class.ClassType\x12\x0e\n\x06lector\x18\x03 \x01(\t\"\x19\n\x04Week\x12\x07\n\x03ODD\x10\x00\x12\x08\n\x04\x45VEN\x10\x01\"7\n\tClassType\x12\x0b\n\x07LECTION\x10\x00\x12\x0e\n\nLABORATORY\x10\x01\x12\r\n\tPRACTICAL\x10\x02\"\x1d\n\x07Shedule\x12\x12\n\x04\x64\x61ys\x18\x01 \x03(\x0b\x32\x04.Day'
)



_DAY_CLASS_WEEK = _descriptor.EnumDescriptor(
  name='Week',
  full_name='Day.Class.Week',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ODD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EVEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=401,
  serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_DAY_CLASS_WEEK)

_DAY_CLASS_CLASSTYPE = _descriptor.EnumDescriptor(
  name='ClassType',
  full_name='Day.Class.ClassType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LECTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LABORATORY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRACTICAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=428,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_DAY_CLASS_CLASSTYPE)


_DAY_CLASS_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Day.Class.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Day.Class.Position.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='week', full_name='Day.Class.Position.week', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=266,
)

_DAY_CLASS_PLACE = _descriptor.Descriptor(
  name='Place',
  full_name='Day.Class.Place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='auditory', full_name='Day.Class.Place.auditory', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='Day.Class.Place.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=310,
)

_DAY_CLASS_CLASSDESCRIPTION = _descriptor.Descriptor(
  name='ClassDescription',
  full_name='Day.Class.ClassDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='Day.Class.ClassDescription.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='Day.Class.ClassDescription.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lector', full_name='Day.Class.ClassDescription.lector', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=399,
)

_DAY_CLASS = _descriptor.Descriptor(
  name='Class',
  full_name='Day.Class',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Day.Class.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='place', full_name='Day.Class.place', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_class', full_name='Day.Class._class', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format', full_name='Day.Class.format', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DAY_CLASS_POSITION, _DAY_CLASS_PLACE, _DAY_CLASS_CLASSDESCRIPTION, ],
  enum_types=[
    _DAY_CLASS_WEEK,
    _DAY_CLASS_CLASSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=483,
)

_DAY = _descriptor.Descriptor(
  name='Day',
  full_name='Day',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Day.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classes', full_name='Day.classes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DAY_CLASS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=483,
)


_SHEDULE = _descriptor.Descriptor(
  name='Shedule',
  full_name='Shedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='days', full_name='Shedule.days', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=485,
  serialized_end=514,
)

_DAY_CLASS_POSITION.fields_by_name['week'].enum_type = _DAY_CLASS_WEEK
_DAY_CLASS_POSITION.containing_type = _DAY_CLASS
_DAY_CLASS_PLACE.containing_type = _DAY_CLASS
_DAY_CLASS_CLASSDESCRIPTION.fields_by_name['type'].enum_type = _DAY_CLASS_CLASSTYPE
_DAY_CLASS_CLASSDESCRIPTION.containing_type = _DAY_CLASS
_DAY_CLASS.fields_by_name['position'].message_type = _DAY_CLASS_POSITION
_DAY_CLASS.fields_by_name['place'].message_type = _DAY_CLASS_PLACE
_DAY_CLASS.fields_by_name['_class'].message_type = _DAY_CLASS_CLASSDESCRIPTION
_DAY_CLASS.containing_type = _DAY
_DAY_CLASS_WEEK.containing_type = _DAY_CLASS
_DAY_CLASS_CLASSTYPE.containing_type = _DAY_CLASS
_DAY.fields_by_name['classes'].message_type = _DAY_CLASS
_SHEDULE.fields_by_name['days'].message_type = _DAY
DESCRIPTOR.message_types_by_name['Day'] = _DAY
DESCRIPTOR.message_types_by_name['Shedule'] = _SHEDULE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Day = _reflection.GeneratedProtocolMessageType('Day', (_message.Message,), {

  'Class' : _reflection.GeneratedProtocolMessageType('Class', (_message.Message,), {

    'Position' : _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
      'DESCRIPTOR' : _DAY_CLASS_POSITION,
      '__module__' : 'shedule_pb2'
      # @@protoc_insertion_point(class_scope:Day.Class.Position)
      })
    ,

    'Place' : _reflection.GeneratedProtocolMessageType('Place', (_message.Message,), {
      'DESCRIPTOR' : _DAY_CLASS_PLACE,
      '__module__' : 'shedule_pb2'
      # @@protoc_insertion_point(class_scope:Day.Class.Place)
      })
    ,

    'ClassDescription' : _reflection.GeneratedProtocolMessageType('ClassDescription', (_message.Message,), {
      'DESCRIPTOR' : _DAY_CLASS_CLASSDESCRIPTION,
      '__module__' : 'shedule_pb2'
      # @@protoc_insertion_point(class_scope:Day.Class.ClassDescription)
      })
    ,
    'DESCRIPTOR' : _DAY_CLASS,
    '__module__' : 'shedule_pb2'
    # @@protoc_insertion_point(class_scope:Day.Class)
    })
  ,
  'DESCRIPTOR' : _DAY,
  '__module__' : 'shedule_pb2'
  # @@protoc_insertion_point(class_scope:Day)
  })
_sym_db.RegisterMessage(Day)
_sym_db.RegisterMessage(Day.Class)
_sym_db.RegisterMessage(Day.Class.Position)
_sym_db.RegisterMessage(Day.Class.Place)
_sym_db.RegisterMessage(Day.Class.ClassDescription)

Shedule = _reflection.GeneratedProtocolMessageType('Shedule', (_message.Message,), {
  'DESCRIPTOR' : _SHEDULE,
  '__module__' : 'shedule_pb2'
  # @@protoc_insertion_point(class_scope:Shedule)
  })
_sym_db.RegisterMessage(Shedule)


# @@protoc_insertion_point(module_scope)
